name: f_grecaptcha
description: Allows accessing the SafetyNet reCaptcha API for android devices in flutter.
version: 1.1.0
homepage: https://github.com/simolus3/f_grecaptcha

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.simolus3.fgrecaptcha
        pluginClass: FGrecaptchaPlugin
